import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Footer from "./component/Footer";
import { Data } from "./types";
import PageWrapper from "./component/PageWrapper";
import { fetchSellerData } from "./lib/utils";
import Navbar from "./component/Navbar";
const geistSans = Geist({
	variable: "--font-geist-sans",
	subsets: ["latin"],
});

const geistMono = Geist_Mono({
	variable: "--font-geist-mono",
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default async function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	const data: Data = await fetchSellerData();
	return (
		<html lang='it' className='w-full h-lvh' data-theme='silk'>
			<body
				className={`${geistSans.variable} ${geistMono.variable} antialiased w-full h-lvh`}>
				<Navbar />
				<PageWrapper>{children}</PageWrapper>
				<Footer sellerData={data.anagrafiche} />
			</body>
		</html>
	);
}
